use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentMeta {
    pub slug: String,
    pub display_name: String,
    pub description: String,
    pub port: u16,
    pub auto_start: bool,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeskConfig {
    pub dashboard_port: u16,
    pub agents: Vec<String>,
}

pub struct ConfigManager {
    pub desk_dir: PathBuf,
}

impl ConfigManager {
    pub fn new(desk_dir: PathBuf) -> Self {
        ConfigManager { desk_dir }
    }

    pub fn agents_dir(&self) -> PathBuf {
        self.desk_dir.join("agents")
    }

    pub fn agent_dir(&self, slug: &str) -> PathBuf {
        self.agents_dir().join(slug)
    }

    pub fn agent_data_dir(&self, slug: &str) -> PathBuf {
        self.agent_dir(slug).join("data")
    }

    pub fn agent_logs_dir(&self, slug: &str) -> PathBuf {
        self.agent_dir(slug).join("logs")
    }

    pub fn agent_meta_path(&self, slug: &str) -> PathBuf {
        self.agent_dir(slug).join("meta.yaml")
    }

    pub fn agent_config_path(&self, slug: &str) -> PathBuf {
        self.agent_dir(slug).join("microclaw.config.yaml")
    }

    pub fn ensure_dirs(&self) -> Result<()> {
        std::fs::create_dir_all(&self.desk_dir)?;
        std::fs::create_dir_all(self.agents_dir())?;
        Ok(())
    }

    pub fn ensure_agent_dirs(&self, slug: &str) -> Result<()> {
        std::fs::create_dir_all(self.agent_dir(slug))?;
        std::fs::create_dir_all(self.agent_data_dir(slug))?;
        std::fs::create_dir_all(self.agent_logs_dir(slug))?;
        Ok(())
    }

    pub fn load_meta(&self, slug: &str) -> Result<AgentMeta> {
        let path = self.agent_meta_path(slug);
        let content = std::fs::read_to_string(&path)?;
        Ok(serde_yaml::from_str(&content)?)
    }

    pub fn save_meta(&self, meta: &AgentMeta) -> Result<()> {
        self.ensure_agent_dirs(&meta.slug)?;
        let path = self.agent_meta_path(&meta.slug);
        let content = serde_yaml::to_string(meta)?;
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn list_agents(&self) -> Result<Vec<AgentMeta>> {
        let mut agents = Vec::new();
        if !self.agents_dir().exists() {
            return Ok(agents);
        }
        for entry in std::fs::read_dir(self.agents_dir())? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                let slug = entry.file_name().to_string_lossy().to_string();
                if let Ok(meta) = self.load_meta(&slug) {
                    agents.push(meta);
                }
            }
        }
        agents.sort_by(|a, b| a.slug.cmp(&b.slug));
        Ok(agents)
    }

    pub fn delete_agent(&self, slug: &str) -> Result<()> {
        let dir = self.agent_dir(slug);
        if dir.exists() {
            std::fs::remove_dir_all(dir)?;
        }
        Ok(())
    }

    pub fn load_microclaw_config(&self, slug: &str) -> Result<String> {
        let path = self.agent_config_path(slug);
        if !path.exists() {
            return Ok(generate_default_config(slug));
        }
        Ok(std::fs::read_to_string(&path)?)
    }

    pub fn save_microclaw_config(&self, slug: &str, content: &str) -> Result<()> {
        self.ensure_agent_dirs(slug)?;
        let path = self.agent_config_path(slug);
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn next_port(&self) -> Result<u16> {
        let agents = self.list_agents()?;
        let max = agents.iter().map(|a| a.port).max().unwrap_or(10960);
        Ok(max + 1)
    }
}

pub fn generate_default_config(slug: &str) -> String {
    format!(
        r#"# Generated by ownify-desk for agent "{slug}"
# Configure your LLM provider and channels below.

llm_provider: "anthropic"
api_key: "sk-ant-..."
model: "claude-sonnet-4-20250514"

data_dir: "~/.ownify-desk/agents/{slug}/data"

web_enabled: true
web_host: "127.0.0.1"
web_port: 0   # ownify-desk will override this

# Optional channels (uncomment to enable):
# channels:
#   telegram:
#     default_account: "main"
#     accounts:
#       main:
#         bot_token: "TELEGRAM_BOT_TOKEN"
#         bot_username: "your_bot"
#
#   discord:
#     default_account: "main"
#     accounts:
#       main:
#         bot_token: "DISCORD_BOT_TOKEN"
#
#   slack:
#     default_account: "main"
#     accounts:
#       main:
#         bot_token: "xoxb-..."
#         app_token: "xapp-..."
#
#   matrix:
#     default_account: "main"
#     accounts:
#       main:
#         homeserver: "https://matrix.org"
#         username: "@your_bot:matrix.org"
#         password: "PASSWORD"
#         auto_join: true
"#,
        slug = slug
    )
}

pub fn is_valid_slug(slug: &str) -> bool {
    !slug.is_empty()
        && slug.len() <= 32
        && slug
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        && !slug.starts_with('-')
        && !slug.ends_with('-')
}
